# Настройки модуля "Склад"

# Метод учёта себестоимости.
# Возможные значения:
#   - "total": Учёт по общему количеству (аналог "по средней" для количества).
#   - "fifo": Партионный учёт (первым пришёл - первым ушёл).
accounting_policy: "fifo" 

# Разрешить ли отрицательные остатки.
# true - можно продать товар "в минус".
# false - продажа сверх остатка будет заблокирована.
allow_negative_stock: false